import React from 'react';
import MobileScroll from 'mobilescroll';

class App extends React.Component {
componentDidMount() {
  import('mobilescroll').then((MobileScroll) => {
    new MobileScroll(
      'body', {} 
    )
});
}
 render() {
  return (
    
    <div className="App">
      

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas, diam ut tempus auctor, ipsum dui blandit urna, vel hendrerit sem orci ac ipsum. Mauris tempor ipsum auctor volutpat placerat. Nunc ut gravida lorem, feugiat varius mi. Sed sagittis rutrum enim eu sodales. Sed nec ornare lectus. Integer viverra, velit ullamcorper facilisis viverra, ipsum velit gravida erat, quis ultricies felis lacus in lectus. Nullam consequat nunc nec elit scelerisque, quis faucibus nisl luctus. Aliquam est erat, sagittis sit amet justo ut, suscipit sagittis mauris. Donec euismod nibh enim, sit amet finibus mauris egestas et. Integer vitae fringilla justo, sit amet mollis massa. Curabitur pharetra egestas odio et facilisis. Etiam neque est, hendrerit in mattis quis, tristique id lorem. Pellentesque dui odio, blandit id nibh nec, mattis posuere nisi. Curabitur in suscipit arcu. Aenean ultricies ex ornare tortor volutpat sodales. Etiam consectetur gravida libero, sed maximus nisi facilisis quis.

Suspendisse maximus leo eu mi fringilla sollicitudin. Aliquam lacinia mi ex, et pharetra felis sodales ac. Suspendisse et ante sed neque efficitur auctor in imperdiet tellus. Donec volutpat fermentum vulputate. Cras vitae scelerisque metus. Vivamus auctor finibus rhoncus. Suspendisse ac tempus velit. Maecenas a efficitur eros. Suspendisse blandit nisl nisl, ac commodo libero pulvinar vitae. Integer gravida erat vitae mauris faucibus, non condimentum nulla gravida. Nulla sed nibh eget justo cursus vestibulum. Praesent at finibus libero. Quisque dictum, quam eget cursus tincidunt, quam odio porta dui, a tristique ex metus et mi. Cras et dui a odio iaculis eleifend. Etiam porta odio aliquet nibh suscipit, quis vestibulum tortor aliquet.

Aliquam erat volutpat. Pellentesque convallis purus urna, quis gravida tellus vestibulum ultricies. Curabitur eleifend mauris nec arcu convallis dapibus. Aenean vestibulum, erat ac hendrerit fermentum, augue justo laoreet est, et placerat justo augue quis risus. Aliquam egestas ante in ante iaculis scelerisque. Aliquam lobortis iaculis leo sit amet volutpat. Praesent eros magna, varius at convallis sed, laoreet vitae magna. Sed sed diam enim. Phasellus metus urna, lacinia placerat interdum nec, commodo id purus. Duis vulputate leo ac elit fermentum, vel dictum elit vehicula. Nunc consectetur lorem malesuada, laoreet est luctus, sagittis ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec magna id dui dapibus rhoncus. Etiam vestibulum metus a velit dictum consectetur sed quis nibh. Phasellus et magna id lacus varius viverra vitae non ligula. Maecenas varius est non sem finibus, eget molestie lorem ultrices.

Quisque porta, diam a maximus hendrerit, augue tortor consequat orci, sit amet ultricies libero leo sit amet odio. Vestibulum massa metus, cursus sed tincidunt vitae, tempor ac nunc. Cras posuere arcu sit amet congue varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis iaculis turpis. Aliquam tristique ac nibh quis luctus. Praesent eros dolor, euismod nec urna quis, ornare egestas nulla.

Suspendisse ex neque, varius eget hendrerit eu, consectetur et velit. Ut in ante sagittis libero pharetra euismod eu sit amet risus. Praesent vel sodales nibh, porttitor pharetra velit. Curabitur lacinia posuere finibus. Duis et congue ipsum. Curabitur nisl erat, auctor at dignissim et, sodales id sem. In non neque in risus scelerisque pretium interdum sit amet tellus. Nam tempus id nulla non varius. Nullam quis orci tortor. Etiam sed ex blandit felis vestibulum dictum in nec eros. Mauris lacus elit, consectetur eget metus ut, tempus fermentum sapien. 
   

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas, diam ut tempus auctor, ipsum dui blandit urna, vel hendrerit sem orci ac ipsum. Mauris tempor ipsum auctor volutpat placerat. Nunc ut gravida lorem, feugiat varius mi. Sed sagittis rutrum enim eu sodales. Sed nec ornare lectus. Integer viverra, velit ullamcorper facilisis viverra, ipsum velit gravida erat, quis ultricies felis lacus in lectus. Nullam consequat nunc nec elit scelerisque, quis faucibus nisl luctus. Aliquam est erat, sagittis sit amet justo ut, suscipit sagittis mauris. Donec euismod nibh enim, sit amet finibus mauris egestas et. Integer vitae fringilla justo, sit amet mollis massa. Curabitur pharetra egestas odio et facilisis. Etiam neque est, hendrerit in mattis quis, tristique id lorem. Pellentesque dui odio, blandit id nibh nec, mattis posuere nisi. Curabitur in suscipit arcu. Aenean ultricies ex ornare tortor volutpat sodales. Etiam consectetur gravida libero, sed maximus nisi facilisis quis.

Suspendisse maximus leo eu mi fringilla sollicitudin. Aliquam lacinia mi ex, et pharetra felis sodales ac. Suspendisse et ante sed neque efficitur auctor in imperdiet tellus. Donec volutpat fermentum vulputate. Cras vitae scelerisque metus. Vivamus auctor finibus rhoncus. Suspendisse ac tempus velit. Maecenas a efficitur eros. Suspendisse blandit nisl nisl, ac commodo libero pulvinar vitae. Integer gravida erat vitae mauris faucibus, non condimentum nulla gravida. Nulla sed nibh eget justo cursus vestibulum. Praesent at finibus libero. Quisque dictum, quam eget cursus tincidunt, quam odio porta dui, a tristique ex metus et mi. Cras et dui a odio iaculis eleifend. Etiam porta odio aliquet nibh suscipit, quis vestibulum tortor aliquet.

Aliquam erat volutpat. Pellentesque convallis purus urna, quis gravida tellus vestibulum ultricies. Curabitur eleifend mauris nec arcu convallis dapibus. Aenean vestibulum, erat ac hendrerit fermentum, augue justo laoreet est, et placerat justo augue quis risus. Aliquam egestas ante in ante iaculis scelerisque. Aliquam lobortis iaculis leo sit amet volutpat. Praesent eros magna, varius at convallis sed, laoreet vitae magna. Sed sed diam enim. Phasellus metus urna, lacinia placerat interdum nec, commodo id purus. Duis vulputate leo ac elit fermentum, vel dictum elit vehicula. Nunc consectetur lorem malesuada, laoreet est luctus, sagittis ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec magna id dui dapibus rhoncus. Etiam vestibulum metus a velit dictum consectetur sed quis nibh. Phasellus et magna id lacus varius viverra vitae non ligula. Maecenas varius est non sem finibus, eget molestie lorem ultrices.

Quisque porta, diam a maximus hendrerit, augue tortor consequat orci, sit amet ultricies libero leo sit amet odio. Vestibulum massa metus, cursus sed tincidunt vitae, tempor ac nunc. Cras posuere arcu sit amet congue varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis iaculis turpis. Aliquam tristique ac nibh quis luctus. Praesent eros dolor, euismod nec urna quis, ornare egestas nulla.

Suspendisse ex neque, varius eget hendrerit eu, consectetur et velit. Ut in ante sagittis libero pharetra euismod eu sit amet risus. Praesent vel sodales nibh, porttitor pharetra velit. Curabitur lacinia posuere finibus. Duis et congue ipsum. Curabitur nisl erat, auctor at dignissim et, sodales id sem. In non neque in risus scelerisque pretium interdum sit amet tellus. Nam tempus id nulla non varius. Nullam quis orci tortor. Etiam sed ex blandit felis vestibulum dictum in nec eros. Mauris lacus elit, consectetur eget metus ut, tempus fermentum sapien. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas, diam ut tempus auctor, ipsum dui blandit urna, vel hendrerit sem orci ac ipsum. Mauris tempor ipsum auctor volutpat placerat. Nunc ut gravida lorem, feugiat varius mi. Sed sagittis rutrum enim eu sodales. Sed nec ornare lectus. Integer viverra, velit ullamcorper facilisis viverra, ipsum velit gravida erat, quis ultricies felis lacus in lectus. Nullam consequat nunc nec elit scelerisque, quis faucibus nisl luctus. Aliquam est erat, sagittis sit amet justo ut, suscipit sagittis mauris. Donec euismod nibh enim, sit amet finibus mauris egestas et. Integer vitae fringilla justo, sit amet mollis massa. Curabitur pharetra egestas odio et facilisis. Etiam neque est, hendrerit in mattis quis, tristique id lorem. Pellentesque dui odio, blandit id nibh nec, mattis posuere nisi. Curabitur in suscipit arcu. Aenean ultricies ex ornare tortor volutpat sodales. Etiam consectetur gravida libero, sed maximus nisi facilisis quis.

Suspendisse maximus leo eu mi fringilla sollicitudin. Aliquam lacinia mi ex, et pharetra felis sodales ac. Suspendisse et ante sed neque efficitur auctor in imperdiet tellus. Donec volutpat fermentum vulputate. Cras vitae scelerisque metus. Vivamus auctor finibus rhoncus. Suspendisse ac tempus velit. Maecenas a efficitur eros. Suspendisse blandit nisl nisl, ac commodo libero pulvinar vitae. Integer gravida erat vitae mauris faucibus, non condimentum nulla gravida. Nulla sed nibh eget justo cursus vestibulum. Praesent at finibus libero. Quisque dictum, quam eget cursus tincidunt, quam odio porta dui, a tristique ex metus et mi. Cras et dui a odio iaculis eleifend. Etiam porta odio aliquet nibh suscipit, quis vestibulum tortor aliquet.

Aliquam erat volutpat. Pellentesque convallis purus urna, quis gravida tellus vestibulum ultricies. Curabitur eleifend mauris nec arcu convallis dapibus. Aenean vestibulum, erat ac hendrerit fermentum, augue justo laoreet est, et placerat justo augue quis risus. Aliquam egestas ante in ante iaculis scelerisque. Aliquam lobortis iaculis leo sit amet volutpat. Praesent eros magna, varius at convallis sed, laoreet vitae magna. Sed sed diam enim. Phasellus metus urna, lacinia placerat interdum nec, commodo id purus. Duis vulputate leo ac elit fermentum, vel dictum elit vehicula. Nunc consectetur lorem malesuada, laoreet est luctus, sagittis ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec magna id dui dapibus rhoncus. Etiam vestibulum metus a velit dictum consectetur sed quis nibh. Phasellus et magna id lacus varius viverra vitae non ligula. Maecenas varius est non sem finibus, eget molestie lorem ultrices.

Quisque porta, diam a maximus hendrerit, augue tortor consequat orci, sit amet ultricies libero leo sit amet odio. Vestibulum massa metus, cursus sed tincidunt vitae, tempor ac nunc. Cras posuere arcu sit amet congue varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis iaculis turpis. Aliquam tristique ac nibh quis luctus. Praesent eros dolor, euismod nec urna quis, ornare egestas nulla.

Suspendisse ex neque, varius eget hendrerit eu, consectetur et velit. Ut in ante sagittis libero pharetra euismod eu sit amet risus. Praesent vel sodales nibh, porttitor pharetra velit. Curabitur lacinia posuere finibus. Duis et congue ipsum. Curabitur nisl erat, auctor at dignissim et, sodales id sem. In non neque in risus scelerisque pretium interdum sit amet tellus. Nam tempus id nulla non varius. Nullam quis orci tortor. Etiam sed ex blandit felis vestibulum dictum in nec eros. Mauris lacus elit, consectetur eget metus ut, tempus fermentum sapien. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas, diam ut tempus auctor, ipsum dui blandit urna, vel hendrerit sem orci ac ipsum. Mauris tempor ipsum auctor volutpat placerat. Nunc ut gravida lorem, feugiat varius mi. Sed sagittis rutrum enim eu sodales. Sed nec ornare lectus. Integer viverra, velit ullamcorper facilisis viverra, ipsum velit gravida erat, quis ultricies felis lacus in lectus. Nullam consequat nunc nec elit scelerisque, quis faucibus nisl luctus. Aliquam est erat, sagittis sit amet justo ut, suscipit sagittis mauris. Donec euismod nibh enim, sit amet finibus mauris egestas et. Integer vitae fringilla justo, sit amet mollis massa. Curabitur pharetra egestas odio et facilisis. Etiam neque est, hendrerit in mattis quis, tristique id lorem. Pellentesque dui odio, blandit id nibh nec, mattis posuere nisi. Curabitur in suscipit arcu. Aenean ultricies ex ornare tortor volutpat sodales. Etiam consectetur gravida libero, sed maximus nisi facilisis quis.

Suspendisse maximus leo eu mi fringilla sollicitudin. Aliquam lacinia mi ex, et pharetra felis sodales ac. Suspendisse et ante sed neque efficitur auctor in imperdiet tellus. Donec volutpat fermentum vulputate. Cras vitae scelerisque metus. Vivamus auctor finibus rhoncus. Suspendisse ac tempus velit. Maecenas a efficitur eros. Suspendisse blandit nisl nisl, ac commodo libero pulvinar vitae. Integer gravida erat vitae mauris faucibus, non condimentum nulla gravida. Nulla sed nibh eget justo cursus vestibulum. Praesent at finibus libero. Quisque dictum, quam eget cursus tincidunt, quam odio porta dui, a tristique ex metus et mi. Cras et dui a odio iaculis eleifend. Etiam porta odio aliquet nibh suscipit, quis vestibulum tortor aliquet.

Aliquam erat volutpat. Pellentesque convallis purus urna, quis gravida tellus vestibulum ultricies. Curabitur eleifend mauris nec arcu convallis dapibus. Aenean vestibulum, erat ac hendrerit fermentum, augue justo laoreet est, et placerat justo augue quis risus. Aliquam egestas ante in ante iaculis scelerisque. Aliquam lobortis iaculis leo sit amet volutpat. Praesent eros magna, varius at convallis sed, laoreet vitae magna. Sed sed diam enim. Phasellus metus urna, lacinia placerat interdum nec, commodo id purus. Duis vulputate leo ac elit fermentum, vel dictum elit vehicula. Nunc consectetur lorem malesuada, laoreet est luctus, sagittis ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec nec magna id dui dapibus rhoncus. Etiam vestibulum metus a velit dictum consectetur sed quis nibh. Phasellus et magna id lacus varius viverra vitae non ligula. Maecenas varius est non sem finibus, eget molestie lorem ultrices.

Quisque porta, diam a maximus hendrerit, augue tortor consequat orci, sit amet ultricies libero leo sit amet odio. Vestibulum massa metus, cursus sed tincidunt vitae, tempor ac nunc. Cras posuere arcu sit amet congue varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis iaculis turpis. Aliquam tristique ac nibh quis luctus. Praesent eros dolor, euismod nec urna quis, ornare egestas nulla.

Suspendisse ex neque, varius eget hendrerit eu, consectetur et velit. Ut in ante sagittis libero pharetra euismod eu sit amet risus. Praesent vel sodales nibh, porttitor pharetra velit. Curabitur lacinia posuere finibus. Duis et congue ipsum. Curabitur nisl erat, auctor at dignissim et, sodales id sem. In non neque in risus scelerisque pretium interdum sit amet tellus. Nam tempus id nulla non varius. Nullam quis orci tortor. Etiam sed ex blandit felis vestibulum dictum in nec eros. Mauris lacus elit, consectetur eget metus ut, tempus fermentum sapien. 
    </div>
   
  );
  
 }
}

export default App;
